### ISSUE TITLE
AAF  past version 2017 no download 

### ISSUE THREAD

**Issue by anthraciteaqualung** [fanhuan/AAF#6]
Hallo FanHuan,
for reasons of comparisons I want to use version [AAF20171001.zip] in my research. When I click on the link in "past versions" it redirects me to a page of source code. Clicking on versions 2016* I find a download button. 
I would appreciate if you could provide access to AAF20171001.zip.

Thank you very much in advance!
Aqualung

**Comment by fanhuan** [comment]
Hi Aqualung, 

Thanks for the heads-up. I just uploaded that file. Please let me know if you have further problem downloading it. 

Best,
Huan
