### ISSUE TITLE
Feedback BetaVersion distance matrix

### ISSUE THREAD

**Issue by anthraciteaqualung** [fanhuan/AAF#7]
Hallo FanHuan, 
the BetaVersion as well as the latest version 2019 doubles the number of sequences in the header of the distance matrix file. This makes it unreadable for e.g. SplitsTree. The result from your test data is: 
#####
10 **10**
sp1       	0	0.08774439038460255	0.17518807382881404	0.08730292323305468	0.08765974685380827	0.08899149001935049	0.08712292543596371	0.04616029487773169	0.12377583510162214	0.16504186033449375
sp10 [...]
#####

I changed to the following and it works perfectly:
####
10
sp1       	0	0.08774439038460255	0.17518807382881404	0.08730292323305468	0.08765974685380827	0.08899149001935049	0.08712292543596371	0.04616029487773169	0.12377583510162214	0.16504186033449375
sp10
#####

Best regards, 
Aqualung

**Comment by fanhuan** [comment]
Hi Aqualung,

The two numbers at the beginning of the distance file are the dimensions of the distance matrix (n by n), which is required by `fitch*` to reconstruct the phylogeny based on it. I'm glad that you were able to change it to the format you like. 

Best,
Huan
